services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database ex_cms_test;' -U postgres
  - nohup phantomjs --wd &
language: elixir
elixir:
  - 1.6.4
otp_release:
  - 20.0
sudo: false
script: mix test --include integration:true
notification:
  recipients:
    - support@larks.in